# Generated by Django 4.0.5 on 2022-06-10 14:17

from django.db import migrations, models
import livro.models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_remove_usuario_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=livro.models.upload_image_livro),
        ),
    ]
